### PR TITLE
Using Jekyll for index page generation

### PR DESCRIPTION
**Pull request by rdumusc**
@eile Please review the new concept.
Once we have validated that Jekyll works as expected on github pages, I will update the CMake logic to deploy the metadata files to the _projects folder via the doxycopy target. Later, we can remove all CMake logic from this repo and eyescale.

### CODE REVIEW

**Comment by eile** [comment]
Can you attach a screenshot please?

**Comment by tribal-tec** [comment]
It's Jekyll, no? Jerk is not nice :)

**Comment by rdumusc** [comment]
Ouch, will fix that! what a weird name anyway :-)

Screenshot:
jekyll

**Comment by rdumusc** [comment]
Can we merge this one too?

**Pull request merged**
